# Embedding settings
embedding_model: "vidore/colpali-v1.3"
device: "cuda"
vit_batch_size: 1

# Vector DB settings
vector_db:
  type: "qdrant"
  host: "localhost"
  port: 6333
  collection_name: "tropical_diseases"
  vector_size: 128
  url: "http://localhost:6333"

# Retrieval
retrieval_top_k: 20

# LLM
llm:
  provider: "huggingface"
  model: "gpt2"

# Paths
paths:
  raw_data: "data/raw/"
  processed_data: "data/processed/"
  db_path: "vector_store/qdrant"
